### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by mlavik1** [mlavik1/UnityVolumeRendering#187]
**TODO:**
- [x] Document all features and formats
- [x] Write more scripting documentation
- [x] Update README, and link to complete documentation
- [x] Make sure generation of PDF documentation (for asset store version) still works fine with new docs.

**Comment by mlavik1** [comment]
Complete documentation: https://github.com/mlavik1/UnityVolumeRendering/blob/master/Documentation/Documentation.md

Documentation as PDF: https://github.com/mlavik1/UnityVolumeRendering/blob/master/MANUAL.pdf
